name: Build and Release libs-only ZIP

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # タグの取得に必要

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"

      - name: Install pip and pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools

      - name: Extract version from tag
        run: |
          $VERSION = $env:GITHUB_REF -replace 'refs/tags/v', ''
          echo "VERSION=$VERSION" >> $env:GITHUB_ENV

      - name: Generate requirements.txt from pyproject.toml
        run: pip-compile --resolver=backtracking --output-file=requirements.txt pyproject.toml

      - name: Install dependencies to libs/
        run: pip install -r requirements.txt -t libs

      - name: Create ZIP of libs only
        run: |
          $ZIP_NAME="msys-shared-deps_libs_v$env:VERSION.zip"
          Compress-Archive -Path libs\* -DestinationPath $ZIP_NAME -Force
          echo "ZIP_NAME=$ZIP_NAME" >> $env:GITHUB_ENV

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
